        "makefile" 11L, 533C                                                                                                                               1,1           All
        OpenBLAS_PATH=/WAVE/projects/ycho_lab/software/OpenBLAS-GCC_12.3.0

        loop:
                g++ -I${OpenBLAS_PATH}/include -L${OpenBLAS_PATH}/lib/ -O3 -o loop loop.cpp -lopenblas
        clean:
                rm loop